Document: mingw-w64-readline
Title: Debian mingw-w64-readline Manual
Author: <insert document author here>
Abstract: This manual describes what mingw-w64-readline is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mingw-w64-readline/mingw-w64-readline.sgml.gz

Format: postscript
Files: /usr/share/doc/mingw-w64-readline/mingw-w64-readline.ps.gz

Format: text
Files: /usr/share/doc/mingw-w64-readline/mingw-w64-readline.text.gz

Format: HTML
Index: /usr/share/doc/mingw-w64-readline/html/index.html
Files: /usr/share/doc/mingw-w64-readline/html/*.html
